openapi: "3.0.2"
info:
  title: Authentication Service
  version: "1.0"
servers:
  - url: https://localhost:8080/api/
paths:
  /auth/register:
    post:
      tags:
        - Auth Service
      summary: Register a new User
      operationId: register
      description: Register a new user and return a JWT token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtToken'
        '400':
          description: Bad Request
        '409':
          description: Conflict
        '500':
          description: Internal Server Error
  
  /auth/login:
    post:
      tags:
        - Auth Service
      summary: Login
      operationId: login
      description: Authenticate existing user and return a JWT token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtToken'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  
  /auth/token:
    post:
      tags:
        - Auth Service
      summary: Request a refresh token
      operationId: token
      description: Request a refresh token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JwtToken'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtToken'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

components:
  schemas:
    
    Login:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    
    Register:
      allOf:
        - $ref: '#/components/schemas/Login'
      type: object
      properties:
        email:
          type: string
      required:
        - username
        - password
        - email
    
    JwtToken:
      type: object
      properties:
        userId:
          type: string
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - userId
        - accessToken
        - refreshToken